//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm operation.
        /// </summary>
        internal static string ConfirmationWindowTitle {
            get {
                return ResourceManager.GetString("ConfirmationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to populate mailboxes in OU &apos;{0}?&apos;.
        /// </summary>
        internal static string ConfirmMailboxPopulationWindowTextFormat {
            get {
                return ResourceManager.GetString("ConfirmMailboxPopulationWindowTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create {0} users in OU &apos;{1}?&apos;.
        /// </summary>
        internal static string ConfirmUserCreationWindowTextFormat {
            get {
                return ResourceManager.GetString("ConfirmUserCreationWindowTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] imdbActresses_txt {
            get {
                object obj = ResourceManager.GetObject("imdbActresses_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailboxes will be created for users in &apos;{0}&apos; who currently don&apos;t have one..
        /// </summary>
        internal static string MailboxCreationInfo {
            get {
                return ResourceManager.GetString("MailboxCreationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping due to errors....
        /// </summary>
        internal static string OpCancelDueToFailure {
            get {
                return ResourceManager.GetString("OpCancelDueToFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation pending....
        /// </summary>
        internal static string OpCancelPending {
            get {
                return ResourceManager.GetString("OpCancelPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requested cancel..
        /// </summary>
        internal static string OpCancelRequested {
            get {
                return ResourceManager.GetString("OpCancelRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Stopped.
        /// </summary>
        internal static string OpStopString {
            get {
                return ResourceManager.GetString("OpStopString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailboxes: {0:N0}, Messages Sent: {1:N0}, Errors: {2:N0}.
        /// </summary>
        internal static string PopulationStatusFormatText {
            get {
                return ResourceManager.GetString("PopulationStatusFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] words_txt {
            get {
                object obj = ResourceManager.GetObject("words_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
